# Web service configuration for Quicker CID Server
services:
  - type: web
    name: quicker-cid-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: quicker-cid-database
          property: connectionString

# Database configuration
databases:
  - name: quicker-cid-database
    databaseName: quicker_cid_db
    user: quicker_user 